name: Workflow CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./Backend/SmartPantry
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./Backend/SmartPantry
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./Backend/SmartPantry

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: '/frontend/package-lock.json'
    - name: Install dependencies
      run: npm install
      working-directory: ./frontend
    - name: Lint code
      run: npm run lint
      working-directory: ./frontend
    - name: Run unit tests
      run: npm test -- --watch=false --browsers=ChromeHeadlessNoSandbox
    - name: Build production application
      run: npm run build -- --configuration=production
    - name: Security audit
      run: npm audit --audit-level=high